#!/bin/sh

build() {
  wasm-pack build --target web --out-name wasm --out-dir ./static
}

start() {
  python3 -m http.server -d ./static 8080 &
  PID=$!
  echo $PID > .serverpid
}

stop(){
    if [ -f .serverpid ]; then
        kill "$(cat .serverpid)"
        rm .serverpid
        echo Server stopped
    else
        echo Could not find the server PID. Is it running?
    fi
}

$1

